grafana:
  # enabled: true
  # admin:
  #   user: admin
  #   password: admin123
  # service:
  #   type: NodePort
  # ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "gce"
  hosts:
    - host: grafana.example.com
      paths:
        - path: /
          pathType: Prefix
  # datasources:
  #   datasources.yaml:
  #     apiVersion: 1
  #     datasources:
  #       - name: Prometheus
  #         type: prometheus
  #         access: proxy
  #         url: http://prometheus-operated.monitoring.svc.cluster.local:9090
  #         isDefault: true
  #         editable: true