apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Values.wordpress.WORDPRESS_DB_HOST }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.wordpress.WORDPRESS_DB_PASSWORD }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.wordpress.WORDPRESS_DB_NAME }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.wordpress.WORDPRESS_DB_USER }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wp-storage
              mountPath: /var/www/html
      volumes:
        - name: wp-storage
          persistentVolumeClaim:
            claimName: wp-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: wordpress
